parameters:
#    wind_core.example.class: Wind\Bundle\CoreBundle\Example

services:
#    wind_core.example:
#        class: %wind_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
